---
- name: Install the required rpms
  yum: name={{ item }} state=latest
  with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - docker
      - python-httplib2
  when: ansible_distribution == "RedHat"

- name: Install the required rpms
  yum: name=NetworkManager state=latest

- name: Start NetworkManager
  service:
    name: NetworkManager
    state: started
    enabled: true
